<?php

namespace AppBundle\Repository;

/**
 * AccountTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
