<?php

namespace AppBundle\Repository;

/**
 * AssetClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetClassRepository extends \Doctrine\ORM\EntityRepository
{
}
