<?php

namespace AppBundle\Repository;

/**
 * ModelAssetClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelAssetClassRepository extends \Doctrine\ORM\EntityRepository
{
}
