<?php

namespace AppBundle\Repository;

/**
 * RiskToleranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiskToleranceRepository extends \Doctrine\ORM\EntityRepository
{
}
