app_homepage:
    path:     /
    defaults: { _controller: AppBundle:App:index }

app_populateModels:
    path:     /populate_models
    defaults: { _controller: AppBundle:App:populateModels }
    methods: [ "POST" ]