services:

    service.accounttype:
        class: AppBundle\Service\AccountTypeService
        arguments: ["@doctrine"]

    service.risktolerance:
        class: AppBundle\Service\RiskToleranceService
        arguments: ["@doctrine"]

    service.model:
        class: AppBundle\Service\ModelService
        arguments: ["@doctrine"]

    #service.url:
        #class: AppBundle\Service\UrlService
#        arguments: ["%app_url%"]